const Colors = {
  MAIN_COLOR: '#66043C',
  MAIN_COLOR_CONTRAST: '#00B2B2',
  MAIN_COLOR_CONTRAST_DARKER: '#009999',
  MAIN_COLOR_CONTRAST_LIGHTER: '#C2E5E5',
  MAIN_COLOR_LIGHT: '#E5DED3',
  MAIN_COLOR_BACKGROUND: '#F5F5F5',
  MAIN_COLOR_DISABLED: '#E5E5E5',
  TEXT_COLOR_PRIMARY: '#1A1917',
  TEXT_COLOR_SECONDARY: '#66625E',
  TEXT_COLOR_DISABLED: '#B2ADA4',
  STATUS_COLOR_WAITING: '#00CFE5',
  STATUS_COLOR_PAID: '#FFE74D',
  STATUS_COLOR_CANCELLED: '#FF7C4D',
  STATUS_COLOR_PROBLEM: '#FF3364',
  STATUS_COLOR_OK: '#2EE59C',
};

export default Colors;
